class Selenium::WebDriver::Remote::Http::Default
  def request: (Symbol, URI::HTTP, Hash[untyped, untyped], nil, ?Integer) -> Selenium::WebDriver::Remote::Response

  def new_request_for: (Symbol, URI::HTTP, Hash[untyped, untyped], nil) -> Net::HTTP::Delete

  def response_for: (Net::HTTP::Delete) -> Net::HTTPOK

  def http: () -> Net::HTTP

  def close: () -> nil
end
