module Selenium
  module WebDriver
    class BiDi
      class SetCookieHeaders
        def initialize: (untyped set_cookie_headers) -> void

        def serialize: () -> (Array[untyped] | untyped)
      end
    end
  end
end
